# A short, descriptive name of this building block collection
name: Data Quality Measures Schemas

# Short abstract for this collection (optional)
abstract: |
  Implementation models (JSON/YAML schemas, but potentially XML and RDF)

# Description for this collection (optional)
description: |
  Data Quality Measures may require complex (non-scalar) value objects, in which case canonical schemas for these values are required to achieve interoperability.

# Customize the following prefix (will be prepended to the path of the building blocks):
identifier-prefix: ogc.dqm.schemas.

# List of imports ("default" is an alias for the main OGC Building Blocks Register)
imports:
  - default

# SPARQL configuration (optional)
#   Authentication can be set through the sparql_username and sparql_password GitHub Workflow inputs
#   (see .github/workflow/process-bblocks.yml)
#
# sparql:
#   push: https://example.com/gsp           # SPARQL Graph Store Protocol endpoint for uploading data
#   graph: https://my.bblocks.example.com/  # SPARQL Graph where data will be uploaded
#                                           #  if left empty, the base URL for the publication will be used
#   query: https://example.com/sparql       # SPARQL query endpoint where data will be available